#!/bin/bash

echo "🔍 Diagnóstico de Firebase Authentication 503"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "El error 503 puede deberse a:"
echo ""
echo "1. ⏱️  Firebase está temporalmente sobrecargado"
echo "   → SOLUCIÓN: Espera 15-30 minutos"
echo ""
echo "2. 🚫 Rate limiting activado en tu IP"
echo "   → SOLUCIÓN: Espera 1 hora o cambia de red"
echo ""
echo "3. 🌐 Problema de red/firewall"
echo "   → SOLUCIÓN: Prueba desde otra red"
echo ""
echo "4. ⚙️  Proyecto Firebase con problemas"
echo "   → SOLUCIÓN: Revisa Firebase Console"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 ACCIONES RECOMENDADAS:"
echo ""
echo "1. Verifica estado de Firebase:"
echo "   https://status.firebase.google.com"
echo ""
echo "2. Espera 30 minutos y vuelve a intentar"
echo ""
echo "3. Prueba desde otro navegador o dispositivo"
echo ""
echo "4. Verifica Firebase Console por alertas:"
echo "   https://console.firebase.google.com/project/tuscitasseguras-2d1a6"
echo ""
echo "5. Si persiste después de 1 hora, contacta soporte Firebase"
echo ""
